'use client'
import './globals.css'
import {useSelectedLayoutSegment} from "next/navigation";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout(props: {
  children: React.ReactNode
  parallel: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    {props.children}
    </body>
    </html>
  )
}
